---
# tasks file for elasticsearch-svr
- name: Add elasticsearch package signing key
  become: true
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add elasticsearch package repository
  become: true
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/{{ elasticsearch.version }}/apt stable main"
    state: present

- name: Update apt cache
  become: true
  apt:
    update_cache: yes

- name: Install elasticsearch apt package
  become: true
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - "elasticsearch"
